from __future__ import annotations

from .comparison import ComparisonFinding, ComparisonReport, EvidenceRef
from .contradiction import Contradiction, contradiction_between
from .correlation import CorrelatedRelation, CorrelationReport, correlate
from .errors import (
    FormatVersionMismatch,
    GapNotFound,
    IdentityCollision,
    IdentityFacts,
    InvalidRelationPair,
    InvalidIdentity,
    InvalidKind,
    KnowledgeError,
    LocatorInvalid,
    MissingRequiredAttribute,
    PayloadInvalid,
    RelationCycle,
    RelationEvidenceRequired,
    RevisionClosed,
    UnknownKind,
    UnknownReference,
    UnsupportedEvidence,
)
from .evidence import (
    CodeContent,
    CodeLocator,
    DiagramLocator,
    DocumentLocator,
    SpreadsheetLocator,
    TranscriptLocator,
    locator_from_dict,
    make_evidence,
)
from .gaps import blocking_gaps, close_gap, is_blocking, open_gap, open_gaps
from .gate import KnowledgeProvenance, KnowledgeRule, KnowledgeViolation
from .gate import check as knowledge_gate
from .grounding import (
    GroundingCheck,
    check_component,
    excerpt_vocabulary,
    key_terms,
    mandatory_terms,
    symbol_defined_or_referenced,
)
from .identity import canonical_name, content_hash, contextual_key, entity_id
from .invalidation import Invalidation, invalidate
from .model import (
    Confidence,
    Entity,
    EntityId,
    KnowledgeState,
    Evidence,
    Locator,
    Relation,
    Revision,
    SourceVersion,
)
from .query import (
    CapabilityProfile,
    FlowStepView,
    ImpactReport,
    KnowledgeQuery,
    PathResult,
)
from .repository import FORMAT_VERSION, KnowledgeRepository, RevisionTransaction
from .taxonomy import (
    ALLOWED_PAIRS,
    REQUIRED_ATTRIBUTES,
    EntityKind,
    RelationKind,
    validate_attributes,
    validate_pair,
)

__all__ = [
    "ALLOWED_PAIRS",
    "CapabilityProfile",
    "CodeContent",
    "CodeLocator",
    "ComparisonFinding",
    "ComparisonReport",
    "Contradiction",
    "CorrelatedRelation",
    "CorrelationReport",
    "Confidence",
    "DiagramLocator",
    "DocumentLocator",
    "Entity",
    "EntityId",
    "EntityKind",
    "KnowledgeState",
    "Evidence",
    "EvidenceRef",
    "FORMAT_VERSION",
    "FlowStepView",
    "FormatVersionMismatch",
    "GapNotFound",
    "GroundingCheck",
    "IdentityCollision",
    "IdentityFacts",
    "ImpactReport",
    "InvalidIdentity",
    "InvalidKind",
    "InvalidRelationPair",
    "Invalidation",
    "KnowledgeError",
    "KnowledgeProvenance",
    "KnowledgeQuery",
    "KnowledgeRepository",
    "KnowledgeRule",
    "KnowledgeViolation",
    "Locator",
    "LocatorInvalid",
    "MissingRequiredAttribute",
    "PathResult",
    "PayloadInvalid",
    "REQUIRED_ATTRIBUTES",
    "Relation",
    "RelationCycle",
    "RelationEvidenceRequired",
    "RelationKind",
    "Revision",
    "RevisionClosed",
    "RevisionTransaction",
    "SourceVersion",
    "SpreadsheetLocator",
    "TranscriptLocator",
    "UnknownKind",
    "UnknownReference",
    "UnsupportedEvidence",
    "blocking_gaps",
    "canonical_name",
    "check_component",
    "close_gap",
    "content_hash",
    "contextual_key",
    "contradiction_between",
    "correlate",
    "entity_id",
    "excerpt_vocabulary",
    "invalidate",
    "is_blocking",
    "key_terms",
    "knowledge_gate",
    "locator_from_dict",
    "make_evidence",
    "mandatory_terms",
    "open_gap",
    "open_gaps",
    "symbol_defined_or_referenced",
    "validate_attributes",
    "validate_pair",
]
